/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppWalletRouteImport } from './routes/_app/wallet'
import { Route as AppVipRouteImport } from './routes/_app/vip'
import { Route as AppTransfersRouteImport } from './routes/_app/transfers'
import { Route as AppSetupRouteImport } from './routes/_app/setup'
import { Route as AppQrRouteImport } from './routes/_app/qr'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppMoneyRouteImport } from './routes/_app/money'
import { Route as AppBankingRouteImport } from './routes/_app/banking'
import { Route as AppAiRouteImport } from './routes/_app/ai'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as ApiStripeCheckoutRouteImport } from './routes/api/stripe/checkout'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppVipRoute = AppVipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => AppRoute,
} as any)
const AppTransfersRoute = AppTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppQrRoute = AppQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMoneyRoute = AppMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AppRoute,
} as any)
const AppBankingRoute = AppBankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiStripeCheckoutRoute = ApiStripeCheckoutRouteImport.update({
  id: '/api/stripe/checkout',
  path: '/api/stripe/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AppAdminRoute
  '/ai': typeof AppAiRoute
  '/banking': typeof AppBankingRoute
  '/money': typeof AppMoneyRoute
  '/profile': typeof AppProfileRoute
  '/qr': typeof AppQrRoute
  '/setup': typeof AppSetupRoute
  '/transfers': typeof AppTransfersRoute
  '/vip': typeof AppVipRoute
  '/wallet': typeof AppWalletRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AppAdminRoute
  '/ai': typeof AppAiRoute
  '/banking': typeof AppBankingRoute
  '/money': typeof AppMoneyRoute
  '/profile': typeof AppProfileRoute
  '/qr': typeof AppQrRoute
  '/setup': typeof AppSetupRoute
  '/transfers': typeof AppTransfersRoute
  '/vip': typeof AppVipRoute
  '/wallet': typeof AppWalletRoute
  '/': typeof AppIndexRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/admin': typeof AppAdminRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/banking': typeof AppBankingRoute
  '/_app/money': typeof AppMoneyRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/qr': typeof AppQrRoute
  '/_app/setup': typeof AppSetupRoute
  '/_app/transfers': typeof AppTransfersRoute
  '/_app/vip': typeof AppVipRoute
  '/_app/wallet': typeof AppWalletRoute
  '/_app/': typeof AppIndexRoute
  '/api/stripe/checkout': typeof ApiStripeCheckoutRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai'
    | '/banking'
    | '/money'
    | '/profile'
    | '/qr'
    | '/setup'
    | '/transfers'
    | '/vip'
    | '/wallet'
    | '/api/stripe/checkout'
    | '/api/public/stripe/webhook'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/ai'
    | '/banking'
    | '/money'
    | '/profile'
    | '/qr'
    | '/setup'
    | '/transfers'
    | '/vip'
    | '/wallet'
    | '/'
    | '/api/stripe/checkout'
    | '/api/public/stripe/webhook'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/_app'
    | '/_app/admin'
    | '/_app/ai'
    | '/_app/banking'
    | '/_app/money'
    | '/_app/profile'
    | '/_app/qr'
    | '/_app/setup'
    | '/_app/transfers'
    | '/_app/vip'
    | '/_app/wallet'
    | '/_app/'
    | '/api/stripe/checkout'
    | '/api/public/stripe/webhook'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiStripeCheckoutRoute: typeof ApiStripeCheckoutRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vip': {
      id: '/_app/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof AppVipRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfers': {
      id: '/_app/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AppTransfersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setup': {
      id: '/_app/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/qr': {
      id: '/_app/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof AppQrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/money': {
      id: '/_app/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof AppMoneyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/banking': {
      id: '/_app/banking'
      path: '/banking'
      fullPath: '/banking'
      preLoaderRoute: typeof AppBankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/stripe/checkout': {
      id: '/api/stripe/checkout'
      path: '/api/stripe/checkout'
      fullPath: '/api/stripe/checkout'
      preLoaderRoute: typeof ApiStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAiRoute: typeof AppAiRoute
  AppBankingRoute: typeof AppBankingRoute
  AppMoneyRoute: typeof AppMoneyRoute
  AppProfileRoute: typeof AppProfileRoute
  AppQrRoute: typeof AppQrRoute
  AppSetupRoute: typeof AppSetupRoute
  AppTransfersRoute: typeof AppTransfersRoute
  AppVipRoute: typeof AppVipRoute
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAiRoute: AppAiRoute,
  AppBankingRoute: AppBankingRoute,
  AppMoneyRoute: AppMoneyRoute,
  AppProfileRoute: AppProfileRoute,
  AppQrRoute: AppQrRoute,
  AppSetupRoute: AppSetupRoute,
  AppTransfersRoute: AppTransfersRoute,
  AppVipRoute: AppVipRoute,
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiStripeCheckoutRoute: ApiStripeCheckoutRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
